---
title: "Supporting information"
author: "Thomas James Ellis, David Luke Field, Nicholas H. Barton"
date: ""
output: pdf_document
header-includes: 
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{S\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{S\arabic{figure}}}
---
\beginsupplement

```{r setup, message=FALSE, echo =FALSE }
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  cache = TRUE,
  cache.lazy = TRUE
)

library(tidyverse)
library(ggpubr)
# library(kable)

# This chunk sets up the prior simulations on dispersal parameters
# See `03_analysis/02_prior_simulations/prior_simulations.Rmd` for more details
source("02_library/R/prior_simulations.R")
source("02_library/R/import_MCMC_results.R")

set.seed(1204 )

```

```{r import-data, cache=TRUE}
# Import all the MCMC results and concatenate into a single data.frame
mcmc_results <- list.dirs("03_analysis/03_mcmc", recursive = FALSE) %>%
  map(import_mcmc_results) %>%
  do.call(what = "rbind") %>%
  filter(iter > 500) %>% # Remove the first 500 iterations as burnin
  # Change the names for each analysis to something human readable
  mutate(
    scenario = recode_factor(
      scenario,
      `01_mcmc_main` = "Mixture allowed",
      `02_no_mixture` = "No mixture"
      )
  )

# Import data table listing mating events
me = read_csv(
  "03_analysis/04_mating_events/output/mating_events_over_chains.csv",
  col_types = 'iccdddddd') %>% 
  left_join( 
    read_csv("01_data/maternal_family_sizes.csv", col_types = 'ci'), by = "mother"
  ) %>% 
  rename(array_size = n_offspring)
```

```{r run-prior-sims, cache=TRUE, cache.lazy=TRUE}
# Set up simulations.
x <- seq(1, 3000, 0.1) # vector of values from 0 to 3000 to draw from
n_draws_per_sim <- 10000 # number of values to draw at each replicate
nsims <- 1000 # number of replicate simulations to run

# Mild skepticism about priors
# Define hyperpriors
prior_values <- list(
  scale = rgamma(shape=2, scale = 100, n = nsims),
  shape = exp(rnorm(mean = -0.7, sd=0.7, n = nsims)),
  sim   = NULL
)

hist(
  rlnorm(nsims, meanlog = -0.7, sdlog=0.5)
)



# run the simulation
prior_values$sim  <- prior_sim(
  x,
  prior_values$scale,
  prior_values$shape,
  n = n_draws_per_sim
)

```

```{r plot-prior-sims, fig.cap="Prior simulations. Histrograms show simulated values for the scale and shape parameters of the generalised normal distribution, and the dispersal distances those imply. Each histogram is summed over 1000 replicate draws from Gamma priors."}

par(mfrow=c(1,3) )#, mar = c(4,4,1, 0))

# Scale parameters
hist(prior_values$scale, breaks = 30,
     main="Scale",
     xlab = "Scale parameter",
     ylab = "Prior density")

# Shape parameters
hist(prior_values$shape, breaks = 30, #xlim=c(0,4), ylim = c(0,120),
     main="Shape",
     ylab = "Prior density",
     xlab = "Shape parameter"
)

# Dispersal distances
hist(prior_values$sim$draws,
     breaks = 30,
     main="Inter-mate distances",
     xlab = "Dispersal distance (m)",
     ylab = "Prior density")

```

```{r prob-family-sizes, fig.cap="Posterior probabilities and sizes of paternal families. Each point shows the mean probability of a mating event between a mother and a single father averaged over 1000 MCMC iterations for the 'restricted-kurtosis' prior scenario, with 96% credible intervals. Colour indicates whether the father was in the sample of candidate or was unsampled. Note that individuals in families with unsampled fathers may consist of multiple paternal families."}

n_iter <- length(unique(me$iter))

me %>% 
  # Keep only mating events with a sampled father
  # filter( !is.na(father) ) %>%
  # mutate(found_father = ifelse(is.na(father), "Sampled candidate", "Missing father")) %>% 
  group_by(mother, father) %>% 
  summarise(
    sibship_size = sum(offspring) / n_iter,
    p = sum(prob) / n_iter,
    p_lower = quantile(prob, 0.02),
    p_upper = quantile(prob, 0.98)
  ) %>% 
  mutate(Sire = ifelse( is.na(father), "Unsampled", "Sampled")) %>% 
  ggplot(aes(y = p, x = sibship_size, colour = Sire)) + 
  geom_point() +
  geom_errorbar( aes( ymin = p_lower, ymax = p_upper )) +
  labs(
    x = "Paternal family size",
    y = "Mean posterior probability"
  ) +
  theme_bw() +
  theme(legend.position = "bottom") +
  facet_grid(rows = vars(Sire))

# me %>% 
#   mutate(Sire = ifelse(is.na(father), "Missing father", "Sampled candidate")) %>% 
#   ggplot( aes(x = offspring, weights = prob, group=Sire, colour=Sire) ) +
#   stat_ecdf(
#     geom = "step",
#     pad = FALSE
#   )
# 

```

```{r distance-vs-prob, fig.cap="Relationship between the distance between mothers and inferred fathers and the posterior probability of the mating event. Points are coloured separately to indicate whether family sizes are less or greater than one.", warning=FALSE}
me %>% 
  group_by(mother, father, distance) %>% 
  summarise(
    prob = mean(prob),
    offspring = mean(offspring)
  ) %>% 
  mutate(`Family size` = ifelse(offspring >=1, "One or more", "Less than one")) %>% 
  ggplot(aes(x=distance, y = prob, colour=`Family size`)) +
  geom_point() +
  labs(
    x = "Inter-mate distance",
    y = "Posterior probability"
  ) + 
  theme_bw()
```


```{r family-sizes, fig.cap="Histogram of paternal family sizes weighted by posterior probability of each family. Data are shown for families with an identifiable father, and those inferred to be sired by an unsampled father. Colours indicate whether weighted-mean family size was more or less than one."}
me %>% 
  mutate(`Family size` = ifelse(offspring <1, "Less than one", "One or more")) %>% 
  group_by(mother, father, `Family size`) %>% 
  summarise(
    sibship_size = sum(offspring) / n_iter,
    p = sum(prob) / n_iter,
    p_lower = quantile(prob, 0.02),
    p_upper = quantile(prob, 0.98)
  ) %>% 
  mutate(Sire = ifelse( is.na(father), "Unsampled", "Sampled")) %>% 
  ggplot(aes(x = sibship_size, weight = p, fill=`Family size`)) + 
  geom_histogram(breaks = seq(0,23,by=1)) +
  labs(
    x = "Sibship size",
    y = "Number of paternal families"
  ) +
  facet_grid(~Sire) +
  theme_bw()

```

```{r nfamilies-vs-array-size, warning=FALSE, fig.cap="Number of paternal families as a function of total maternal array size. Data shown for the 'restricted-kurtosis' prior scenario and are averaged over 1000 iterations of the MCMC. Also plotted is curve predicted from a Poisson GLM of family number on array size, constrained to go through zero at the intercept."}
# Average the probability of mating events having occurred over each iteration 
# of the MCMC.
mean_me <- me %>% 
  # Keep only mating events with a sampled father, and with at least two offspring
  # (offspring number is weighted by the probability of having occurred, so 
  # this may be less than 1.)
  filter(!is.na(father)) %>% 
  # Average over iterations
  group_by(mother, array_size) %>% 
  summarise(
    n = (sum(prob) / length(unique(me$iter))),
    # n_plus_1 = n + 1,
    .groups = "drop_last"
  ) %>% 
  ungroup()

# Poisson GLM for the number of mating events as a function of the number of 
# progeny in the maternal family.
mod <- glm(n ~ array_size, data = mean_me, family = poisson)
# Dataframe giving predicted number of mating events for maternal families of
# 1 to 30 from the GLM
pframe <- data.frame(
  array_size = 1:30
) %>% 
  mutate(
    n = predict(mod, newdata = ., type = 'response')
  )


mean_me %>% 
  ggplot( aes( x=array_size, y = n )) +
  geom_point() +
  geom_line(data = pframe, aes(x = array_size, y = n)) + 
  labs(
    x = "Maternal-array size",
    y = "Number of paternal families"
  ) +
  theme_bw()

```

```{r caterpillar-plots, fig.cap="Change in log posterior density over four independent MCMC chains. The first 500 iterations of each chain have been removed as burn-in.", fig.width=22/2.54, include=TRUE}

# Plot the change in log posterior through time
mcmc_results %>%
  filter(scenario == "Mixture allowed") %>% 
  ggplot(aes(x = iter, y = log_posterior, colour = chain, groups = chain)) +
  geom_line() +
  labs(
    x = "Iteration",
    y = "Log posterior"
  ) +
  # facet_grid(~ scenario) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r no-mixture, fig.width=16.9/2.54, fig.height=8/2.54, fig.cap = "Posterior densities for the shape and scale parameters of the dispersal kernel for a model where the mixture parameter is fixed to one. Histograms show stacked densities for each of four independent chains."}

posterior_density <- list(
  scale = mcmc_results %>%
    filter(scenario == "No mixture") %>% 
    ggplot(aes(x = scale, colour = chain, groups=chain, fill = chain)) +
    geom_histogram() +
    labs(
      x = "Scale",
      y = "Posterior density"
    ) +
    theme_bw(),
  
  shape = mcmc_results %>%
    filter(scenario == "No mixture") %>% 
    ggplot(aes(x = shape, colour = chain, groups=chain, fill = chain)) +
    geom_histogram() +
    labs(
      x = "Shape",
      y = ""
    ) +
    theme_bw()
)

ggarrange(
  plotlist = posterior_density,
  ncol = 2,
  common.legend = TRUE,
  legend = "bottom"
)

```

```{r sd-gnd, fig.cap="Mean dispersal distances implied by the second moment of the generalised normal distribution based on scale and shape parameters from MCMC chains for six prior scenarios."}

# Function to calculate the mean dispersal distance as the 2nd moment of the 
# generalised normal distribution
stdev_GND <- function(a,b){
  sqrt(
    (a^2 * gamma(3/b) ) / gamma(1/b)
  )
}

# Function to plot means and credible intervals from the object created above.
plot_parameter <- function(p, ylab){
  mcmc_summary %>% 
    filter(parameter == p) %>% 
    ggplot(aes( y = mean, x = scenario)) +
    geom_point() +
    geom_errorbar(aes( ymin=lower, ymax=upper), width=0.1 ) +
    labs(
      x = element_blank(),
      y = ylab
    ) +
    theme_bw()
}

mcmc_results$sd <- stdev_GND(mcmc_results$scale, mcmc_results$shape)

mcmc_results %>%
  group_by(scenario) %>% 
  summarise(
    mean = mean(sd),
    lower = quantile(sd, 0.02),
    upper = quantile(sd, 0.98)
  ) %>% 
  ggplot(aes( y = mean, x = scenario)) +
    geom_point() +
    geom_errorbar(aes( ymin=lower, ymax=upper), width=0.1 ) +
    labs(
      x = element_blank(),
      y = "Mean dispersal distance (m)"
    ) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, size = 8)
    )
```

```{r, fig.height=20/2.54, fig.width=16.9/2.54, fig.cap="Proportion of offspring assigned to missing fathers in simulated data. Panels show the proportion of true fathers missing from the dataset used to infer mating events (columns) and the true full sibship size (rows). Values are the mean of 100 replicate simulations, and are shown for inference using paternity (Pat) only, paternity and sibships (sibs), and paternity, sibships and dispersal information."}

sim_mating_events <- read_csv(
  "03_analysis/05_simulations/output/sims_mating.csv",
  col_types = 'ffidifddddddddd'
  )

sim_mating_events <- sim_mating_events %>% 
  group_by(scale, nloci, prop_purged, family_size, data_type) %>% 
  summarise(
    true_pos  = mean(true_if_offs_ge1, na.rm = TRUE),
    false_neg = mean(true_if_offs_lt1, na.rm = TRUE),
    missing = mean(missing, na.rm = TRUE)
  ) %>% 
  # Rejig the variables to make them plot nicely.
  mutate(
    scale = paste0(scale, "m"),
    prop_purged = paste0(prop_purged*100, "% missing fathers"),
    family_size = paste0(family_size, " siblings"),
    data_type = case_when(
      data_type == "paternity" ~ "Paternity only",
      data_type == "sibships" ~ "Pat., sibships",
      data_type == "full" ~ "Pat., sibs., dispersal"
    )
  ) %>% 
  rename(
    `Mean dispersal` = scale,
    Inference = data_type
  )

# plot_ge1 <- 
sim_mating_events %>% 
  ggplot(aes(x=nloci, y=missing, colour=Inference, linetype=`Mean dispersal`)) +
  geom_line() +
  geom_point() +
  labs(
    x = "Number of markers",
    y = "Proportion assigned missing"
  ) +
  theme_bw() +
  facet_grid(family_size~prop_purged)
```

